"use client";

/**
 * NarrativeChronicle — Persistent storybook sidebar that accumulates events
 * as the user mines. Shows a scrollable chronicle of all narrative events
 * generated by the AI World Engine, styled like a pixel-art book.
 *
 * Unlike NarrativePanel (15s popup), this component shows the FULL history
 * and updates in real-time as new events arrive from mining.
 */

import { useEffect, useRef, useState, useMemo } from "react";
import { useNarrativeStore } from "@bitcoinbaby/core";
import type {
  NarrativeEvent,
  NarrativeEventType,
  BabyNFTState,
} from "@bitcoinbaby/ai";
import { NarrativeEngine } from "@bitcoinbaby/ai";
import { clsx } from "clsx";

// =============================================================================
// EVENT TYPE ICONS & COLORS
// =============================================================================

const EVENT_ICONS: Record<NarrativeEventType, string> = {
  LORE: "📖",
  DISCOVERY: "💡",
  TECHNICAL: "🔧",
  SOCIAL: "💬",
  MYSTICAL: "✨",
  EVOLUTION: "⚡",
};

const EVENT_COLORS: Record<NarrativeEventType, string> = {
  LORE: "#f7931a",
  DISCOVERY: "#4ade80",
  TECHNICAL: "#4fc3f7",
  SOCIAL: "#ffc107",
  MYSTICAL: "#c084fc",
  EVOLUTION: "#facc15",
};

const EVENT_LABELS: Record<NarrativeEventType, string> = {
  LORE: "LORE",
  DISCOVERY: "DISCOVERY",
  TECHNICAL: "TECH",
  SOCIAL: "SOCIAL",
  MYSTICAL: "MYSTIC",
  EVOLUTION: "EVOLVE",
};

// =============================================================================
// SUB-COMPONENT: Single Chronicle Entry
// =============================================================================

function ChronicleEntry({
  event,
  isNew,
}: {
  event: NarrativeEvent;
  isNew: boolean;
}) {
  const color = EVENT_COLORS[event.type] ?? "#f7931a";
  const icon = EVENT_ICONS[event.type] ?? "📖";
  const label = EVENT_LABELS[event.type] ?? "EVENT";

  return (
    <div
      className={clsx(
        "flex gap-2 py-2 px-2 border-b border-pixel-border/30 transition-all duration-500",
        isNew && "bg-pixel-primary/10 animate-pulse-once",
      )}
      style={{
        fontFamily: "'Pixelify Sans', sans-serif",
      }}
    >
      {/* Event icon + color bar */}
      <div className="flex-shrink-0 flex flex-col items-center gap-1 pt-0.5">
        <span className="text-xs">{icon}</span>
        <span
          className="text-[7px] font-pixel leading-none"
          style={{ color, fontFamily: "'Press Start 2P', monospace" }}
        >
          {label}
        </span>
      </div>

      {/* Event content */}
      <div className="flex-1 min-w-0">
        <div
          className="text-[11px] leading-relaxed"
          style={{ color: "#e5e7eb" }}
        >
          {event.title}
        </div>
        {event.description && (
          <div
            className="text-[10px] leading-relaxed mt-0.5"
            style={{ color: "#9ca3af" }}
          >
            {event.description}
          </div>
        )}
        {/* Model badge */}
        {event.modelUsed && (
          <div className="mt-1">
            <span
              className="text-[7px] px-1 py-0.5 rounded"
              style={{
                background: "rgba(255,255,255,0.05)",
                color: "#6b7280",
                fontFamily: "'VT323', monospace",
              }}
            >
              {event.modelUsed}
            </span>
          </div>
        )}
      </div>

      {/* Timestamp */}
      <div className="flex-shrink-0 text-[8px] text-pixel-text-muted pt-0.5">
        {new Date(event.timestamp).toLocaleTimeString([], {
          hour: "2-digit",
          minute: "2-digit",
          second: "2-digit",
        })}
      </div>
    </div>
  );
}

// =============================================================================
// MAIN COMPONENT
// =============================================================================

export interface NarrativeChronicleProps {
  /** Token ID of the active baby NFT */
  tokenId: number | null;
  /** NFT state for initializing the narrative store */
  nftState: BabyNFTState | null;
  /** Optional className */
  className?: string;
}

export function NarrativeChronicle({
  tokenId,
  nftState,
  className,
}: NarrativeChronicleProps) {
  const scrollRef = useRef<HTMLDivElement>(null);
  const [lastSeenCount, setLastSeenCount] = useState(0);

  // Initialize narrative store for this baby if needed
  const narrativeStore = useNarrativeStore();
  useEffect(() => {
    if (tokenId !== null && nftState) {
      narrativeStore.getOrCreate(
        tokenId,
        NarrativeEngine.initNarrativeState(nftState),
      );
    }
  }, [tokenId, nftState, narrativeStore]);

  // Subscribe to narrative store for this tokenId
  const events = useNarrativeStore((s) => {
    if (tokenId === null) return [];
    return s.states[tokenId]?.events ?? [];
  });

  // Track which events are "new" (arrived since last render)
  const newEventIds = useMemo(() => {
    if (events.length <= lastSeenCount) return new Set<string>();
    const newIds = new Set<string>();
    for (let i = lastSeenCount; i < events.length; i++) {
      newIds.add(events[i].id);
    }
    return newIds;
  }, [events, lastSeenCount]);

  // Auto-scroll to bottom when new events arrive
  useEffect(() => {
    if (events.length > lastSeenCount && scrollRef.current) {
      scrollRef.current.scrollTo({
        top: scrollRef.current.scrollHeight,
        behavior: "smooth",
      });
      setLastSeenCount(events.length);
    }
    // eslint-disable-next-line react-hooks/exhaustive-deps -- lastSeenCount is intentionally excluded to avoid loops
  }, [events.length]);

  // Empty state
  if (!tokenId) {
    return (
      <div className={clsx("p-4 text-center", className)}>
        <div className="font-pixel text-[9px] text-pixel-text-muted">
          No baby selected
        </div>
        <div className="font-pixel text-[7px] text-pixel-text-muted mt-1">
          Mint a Genesis Baby NFT to begin your story.
        </div>
      </div>
    );
  }

  if (events.length === 0) {
    return (
      <div className={clsx("p-4 text-center", className)}>
        <div className="text-2xl mb-2">📖</div>
        <div className="font-pixel text-[9px] text-pixel-text-muted">
          The Chronicle Awaits
        </div>
        <div className="font-pixel text-[7px] text-pixel-text-muted mt-1">
          Start mining to write your baby&apos;s story.
        </div>
      </div>
    );
  }

  return (
    <div
      ref={scrollRef}
      className={clsx("overflow-y-auto", "scrollbar-thin", className)}
      style={{
        maxHeight: "400px",
        scrollbarWidth: "thin",
        scrollbarColor: "#374151 transparent",
      }}
    >
      {/* Chronicle header */}
      <div
        className="sticky top-0 z-10 px-3 py-2 flex items-center justify-between"
        style={{
          background: "linear-gradient(180deg, #0d1117 80%, transparent)",
          borderBottom: "1px solid #1f2937",
          fontFamily: "'Press Start 2P', monospace",
          fontSize: 9,
          color: "#f7931a",
        }}
      >
        <span>📖 BABY CHRONICLE</span>
        <span
          style={{
            fontSize: 8,
            color: "#6b7280",
            fontFamily: "'VT323', monospace",
          }}
        >
          {events.length} entries
        </span>
      </div>

      {/* Event list */}
      <div className="px-1">
        {events.map((event) => (
          <ChronicleEntry
            key={event.id}
            event={event}
            isNew={newEventIds.has(event.id)}
          />
        ))}
      </div>

      {/* Mining indicator */}
      <div
        className="text-center py-2 text-[8px] font-pixel"
        style={{ color: "#374151" }}
      >
        ●●● MINING IN PROGRESS ●●●
      </div>
    </div>
  );
}

export default NarrativeChronicle;
